version: '3.7'

services:

  web:
    container_name: web_moat
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    depends_on:
      - db

  db:
    container_name: postgres_moat
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    container_name: nginx_moat
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
