version: "3.7"

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - envs/.dev.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
    entrypoint:
      - sh
      - /app/entrypoint.sh

  db:
    container_name: postgres
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
