# Generated by Django 3.1.5 on 2021-02-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('canceled', 'canceled')], default='pending', max_length=12)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clubs.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
