name: Deploy dev branch to EC2
on:
  push:
    branches:
    - develop
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@develop

    - name: create env file
      run: |
        mkdir envs
        touch .env
        echo "${{ secrets.ENV }}" >> envs/.env
        touch .env.prod
        echo "${{ secrets.ENV_PROD }}" >> envs/.env.prod
        touch .env.prod.proxy-companion
        echo "${{ secrets.ENV_PROXY }}" >> envs/.env.prod.proxy-companion

    - name: create remote directory
      uses: appleboy/ssh-action@develop
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: mkdir -p /home/ubuntu/srv/${{ secrets.DEPLOY_USERNAME }}

    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/${{ secrets.DEPLOY_USERNAME }}/
        remote_host: ${{ secrets.HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.KEY }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@develop
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          export DEPLOY_USERNAME=${{ secrets.DEPLOY_USERNAME }}
          sh /home/ubuntu/srv/${{ secrets.DEPLOY_USERNAME }}/config/scripts/deploy.sh
